# Generated by Django 5.0.4 on 2024-04-28 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectApp', '0003_vacancy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacancy',
            old_name='project_id',
            new_name='project',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='title',
            field=models.CharField(default='Job title', max_length=255),
        ),
    ]
