# Generated by Django 5.0.4 on 2024-04-26 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profil',
            name='country',
        ),
    ]
