# Generated by Django 5.0.4 on 2024-04-26 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0002_remove_profil_country'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.AlterField(
            model_name='profil',
            name='role',
            field=models.CharField(choices=[('programmer', 'programmer'), ('startup', 'startup')], max_length=15),
        ),
    ]
