# Generated by Django 5.0.4 on 2024-04-28 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0003_delete_country_alter_profil_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='role',
            field=models.CharField(choices=[('programmer', 'programmer'), ('startup', 'startup'), ('investor', 'investor')], max_length=15),
        ),
    ]
