# Generated by Django 5.0.4 on 2024-04-28 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0004_alter_profil_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='job_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
