# Generated by Django 5.0.4 on 2024-04-26 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commentApp', '0001_initial'),
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.project'),
        ),
    ]
